### ISSUE TITLE
Change db id to Number type

### ISSUE THREAD

**Issue by panbenson** [BrandonWeng/padevo#10]
Can't sort entries right now (they are just cast from String to Number in the screenshot below)

<img width="627" alt="screen shot 2017-07-27 at 8 58 33 pm" src="https://user-images.githubusercontent.com/15132025/28698041-900833ba-730e-11e7-8e32-98710912c1d9.png">

Could you please change the type of id column to Number?

**Comment by BrandonWeng** [comment]
Will do, do you want me to do the same for the materials?

**Comment by panbenson** [comment]
yes pls, I think it will be more consistent in case we use it for queries or something else too

**Comment by BrandonWeng** [comment]
done!
